### ISSUE TITLE
Ensure Token List Parity

### ISSUE THREAD

**Issue by 59023g** [Sifchain/big-dipper#24]
There are new tokens in the Dex not in the Block Explorer config. This causes values to show up as undefined.
<img width="996" alt="Screen Shot 2021-05-03 at 6 31 14 PM" src="https://user-images.githubusercontent.com/5235538/116945623-c0a5b580-ac3d-11eb-8ab3-928ef9f1f6d8.png">

**Comment by caseyturnerarrington** [comment]
@59023g reference here for some more examples: https://github.com/Sifchain/issues/issues/389

**Comment by caseyturnerarrington** [comment]
So just to make sure I am clear: every time we add a new token, we also need to add it to the blockexplorer?
