### ISSUE TITLE
LM & VS Dispensations Not Displaying in Distribution Panel

### ISSUE THREAD

**Issue by mccallofthewild** [Sifchain/big-dipper#35]
**Describe the bug**
User `sif1vvf0n2kvq0qxvl209xe4rhnk3ykg5mjcdya9yq` claimed and received rewards for both Liquidity Mining and Validator Subsidy programs yet these transactions are not displaying in the distribution panel under `/accounts/<ADDRESS>`.
We know that this user received their rewards because they have already swapped their earnings for cETH and unpegged.

**To Reproduce**
1. Go to https://blockexplorer.sifchain.finance/account/sif1vvf0n2kvq0qxvl209xe4rhnk3ykg5mjcdya9yq
2. Scroll down to "Transactions" section
3. Click on `Distribution`
4. Observe that there are no transactions listed
5. Navigate to https://cryptoeconomics.sifchain.finance/#sif1vvf0n2kvq0qxvl209xe4rhnk3ykg5mjcdya9yq&snapshot-source=mainnet&type=lm
6. Observe that they have received >=25,024.31 Rowan in rewards

**Expected behavior**
Distributed LM, VS, and Airdrop rewards should display under the "Distribution" panel

**Comment by mccallofthewild** [comment]
Need to add `distribution/create`, `distribution/run`, and `distribution/claim`  events to: https://github.com/Sifchain/big-dipper/blob/c7c0bd4cb033fa58d11965999d92c30afbbeff24/imports/ui/components/TransactionsContainer.js#L60-L66

**Comment by mccallofthewild** [comment]
cc: @caseyturnerarrington

**Comment by mccallofthewild** [comment]
Exact dispensation event names can be found here:
https://github.com/Sifchain/Vanir/blob/5e2933b61ab2439b30dd30c979a2621c02d8f664/utils.py#L308-L493

**Comment by ajoslin** [comment]
I'll take a look
